-- users 테이블 생성
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  isLoggedIn BOOLEAN DEFAULT FALSE,
  isActive BOOLEAN DEFAULT TRUE,
  failedLoginAttempts INT DEFAULT 0,
  lastLoginAttempt DATETIME NULL,
  ipAddress VARCHAR(45) NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 인덱스 생성 (검색 성능 향상)
CREATE INDEX idx_username ON users(username);

